version: '3'

services:
  web:
    build: .
    command: bash -c "sleep 1 && python3 main.py -c deployment/config/user_config.toml"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres

  redis:
    restart: always
    image: redis:latest
    privileged: true
    command: bash -c "sysctl vm.overcommit_memory=1 && redis-server"
    ports:
      - "6379:6379"
